name: Update dataset

on:
  schedule:
    # Update Thu 04:15 (CST) per week
    - cron: "15 20 * * 3"
  workflow_dispatch: {}

jobs:
  update_dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y lua5.4
          sudo npm install -g pnpm
          pnpm install

      - name: Build & Validate
        run: |
          node scripts/to-esm.mjs mjs
          bash scripts/buildAndValidate.sh
          node scripts/updateVendorStrings.mjs

      - name: Commit files
        continue-on-error: true
        run: |
          node scripts/to-esm.mjs cjs
          git config --local user.email "noreply@outv.im"
          git config --local user.name "GitHub Actions"
          git add data/ locales/
          git commit -m "feat: update dataset"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
